# Generated by Django 4.2 on 2025-04-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_billitem_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='hsn_code',
            field=models.IntegerField(default=5407),
        ),
    ]
