# Generated by Django 4.2 on 2025-04-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_billitem_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='latest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
