# Generated by Django 4.2 on 2025-04-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_billitem_rate_alter_product_latest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='hsn_code',
        ),
        migrations.AddField(
            model_name='bill',
            name='hsn_code',
            field=models.IntegerField(default=5208),
        ),
    ]
