# Generated by Django 4.2 on 2025-04-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_billitem_hsn_code_bill_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount_in_words',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='bill',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
