# Generated by Django 4.2 on 2025-04-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bill_amount_in_words_alter_bill_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
