# Generated by Django 4.2 on 2025-04-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_billitem_product_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='gstin',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
