# Generated by Django 4.2 on 2025-04-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_buyer_gstin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='hsn_code',
        ),
        migrations.AddField(
            model_name='billitem',
            name='hsn_code',
            field=models.IntegerField(default=5208),
        ),
    ]
