# Generated by Django 4.2 on 2026-07-02 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_bill_hsn_code_billitem_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
